---
title: "Athlete Activities Analysis"
author: "Peter Bonner"
date: "15/04/2021"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(cache = TRUE, warning = FALSE,
                      message = FALSE,echo = TRUE, dpi = 180,
                      fig.width = 8, fig.height = 5)


```

## Libraries
```{r}
library(tidyverse)
library(readr)
library(janitor)
library(readxl)
library(lubridate)
theme_set(theme_minimal())

```

## Read data
```{r}
activities <- read_csv("data/activities.csv") %>%
  mutate(date = as_date(date),
           year = year(date),
         quarter = quarter(date))


```

## Filter Data

```{r}
options(scipen = 999)

# Activites per year
activities %>%
  filter(sport == "Bike") %>%
  ggplot(aes(x = factor(year))) +
  geom_histogram(binwidth = 1, stat = "count") +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  labs(title = "Activities uploaded per year",
       x = "Year") 
  
```


```{r}
activities_filtered <- activities %>%
  filter(sport == "Bike") %>%
  filter(age >= 18 & age <= 60) %>%
  filter(`1s_critical_power` != 2000,
         `1s_critical_power` != 1000) %>%
         group_by(gender) %>%
           filter(`1s_critical_power` < quantile(`1s_critical_power`,0.99, na.rm = TRUE),
                  `15s_critical_power` < quantile(`1s_critical_power`,0.99, na.rm = TRUE),
                  `2m_critical_power` < quantile(`3m_critical_power`, 0.99, na.rm = TRUE),
                  `3m_critical_power` < quantile(`3m_critical_power`, 0.99, na.rm = TRUE),
                  `5m_critical_power` < quantile(`5m_critical_power`, 0.99, na.rm = TRUE),
                  `8m_critical_power` < quantile(`8m_critical_power`, 0.99, na.rm = TRUE),
                  `10m_critical_power` < quantile(`8m_critical_power`, 0.99, na.rm = TRUE),
                  `20m_critical_power` < quantile(`8m_critical_power`, 0.99, na.rm = TRUE),
                  `30m_critical_power` < quantile(`8m_critical_power`, 0.99, na.rm = TRUE))
         
```

## Quarterly best MMPs

```{r}
# Extract max MMP values for each quarter per year 
activities_quarters <- activities_filtered %>%
  group_by(id,year,quarter) %>%
  summarise(across(c(`3m_critical_power`:`10m_critical_power`), max))
```


# Critical power model

```{r}
library(tidymodels)
# Convert to long format
activities_quarters_long <- activities_quarters %>%
  dplyr::rename(`180` = `3m_critical_power`,
                `300` = `5m_critical_power`,
                `480` = `8m_critical_power`,
                `600` = `10m_critical_power`) %>%
  pivot_longer(`180`:`600`, names_to = "duration_s", values_to = "power_output") %>%
  mutate(duration_s = as.numeric(duration_s),
    work_done = duration_s * power_output)

# Nest model data
activities_quarters_nest <- activities_quarters_long %>%
  group_by(id,year,quarter) %>%
  nest(data = c(duration_s,power_output,work_done))

# iterate linear cp model
cp_model <- activities_quarters_nest %>%
  mutate(model = map(data, ~lm(work_done ~ duration_s, data = .x)))

## iterate over the model with the function tidy (which puts lm output into tidy format) & unnest coeffs to extract cp & wprime into separate columns

activities_cp <- cp_model %>%
  rowwise() %>% 
  mutate(
    coefs = broom::tidy(model) %>% list()
  ) %>% 
  ungroup() %>% 
  select(id, year,quarter,coefs) %>% 
  unnest(cols = coefs) %>% 
  mutate(
    term = ifelse(term == "(Intercept)", "w_prime", "critical_power")
  ) %>% 
  select(id:std.error) %>% 
  pivot_longer(cols = c("estimate", "std.error")) %>% 
  mutate(
    term = ifelse(name == "estimate", term, paste(term, "error", sep = "_"))
  ) %>% 
  select(-name) %>% 
  pivot_wider(names_from = term) %>% 
  left_join(x = activities_filtered, 
            y = .,
            by = c("id", "year","quarter")) %>% 
  ## Remove dodgy wprime and cp values
  filter(w_prime > 1000,
         w_prime < 50000) %>%
  filter(critical_power > 100,
         critical_power < 500)

```

## Average change in CP over time

```{r}
# calculate % change in cp and wprime per quarter
cp_stats <- cp_model %>%
  rowwise() %>% 
  mutate(
    coefs = broom::tidy(model) %>% list()
  ) %>% 
  ungroup() %>% 
  select(id, year,quarter,coefs) %>% 
  unnest(cols = coefs) %>% 
  mutate(
    term = ifelse(term == "(Intercept)", "w_prime", "critical_power")
  ) %>% 
  select(id:std.error) %>% 
  pivot_longer(cols = c("estimate", "std.error")) %>% 
  mutate(
    term = ifelse(name == "estimate", term, paste(term, "error", sep = "_"))
  ) %>% 
  select(-name) %>% 
  pivot_wider(names_from = term) %>%
  # Filter dodgy values
  filter(w_prime > 1000 & w_prime < 50000) %>%
  filter(critical_power > 100 & critical_power < 500) %>%
# calculate % change in cp/w_prime for each quarter per person
  group_by(id) %>%
  arrange(year, quarter, .by_group = TRUE) %>%
  mutate(cp_pct_change = (critical_power / lag(critical_power)-1)*100,
         w_prime_pct_change = (w_prime / lag(w_prime)-1)*100)

# change in cp per quarter
cp_stats %>%
  filter(year > 1999 & year <= 2021) %>%
  group_by(year) %>%
  summarise(avg_change = mean(cp_pct_change, na.rm = TRUE)) %>%
  arrange(avg_change) %>%
  ggplot(aes(x = factor(year), y = avg_change)) +
  geom_col(fill = "#f03b20", alpha = 0.5) +
  labs(title = "Average percent change in critical power per quarter",
       x = NULL,
       y = NULL)

# change in wprime per quarter
cp_stats %>%
  filter(year > 1999 & year <= 2021) %>%
  group_by(year) %>%
  summarise(avg_change = mean(w_prime_pct_change, na.rm = TRUE)) %>%
  arrange(avg_change) %>%
  ggplot(aes(x = factor(year), y = avg_change)) +
  geom_col(fill = "#f03b20", alpha = 0.5) +
  labs(title = "Average percent change in W' per quarter",
       x = NULL,
       y = NULL)

# individual change over time

```

