---
title: "Activities CP - Vis and Analysis"
author: "Peter Bonner"
date: "19/04/2021"
output: html_document
editor_options: 
  chunk_output_type: console
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(cache = TRUE, warning = FALSE,
                      message = FALSE,echo = TRUE, dpi = 180,
                      fig.width = 8, fig.height = 5)


```

```{r}
library(tidyverse)
library(readr)
library(janitor)
library(readxl)
library(lubridate)
theme_set(theme_minimal())
library(GGally)
library(broom)

options(scipen = 999)
```


## Read in activities data
```{r}
activities_cp <- read_rds("~/R/gc_open_data/data/activities_cp.rds") %>%
  relocate(year:`30m_critical_power`,
           .after = where(is.character)) %>%
  mutate(year = as.factor(year)) %>%
  select(-X34)


```

# Training metrics by quarter

```{r}
# Quarterly totals for volume measures
quarter_totals <- activities_cp %>%
  mutate(year = as.factor(year)) %>%
  group_by(id,year,quarter) %>%
  summarise(across(c("workout_time_min","total_distance","elevation_gain","total_work"), ~ sum(.x, na.rm = TRUE),.names = "total_{.col}"),.groups = "keep")

# quarter averages for intensity measures
quarter_averages <- activities_cp %>%
  mutate(year = as.factor(year)) %>%
  group_by(id,year,quarter) %>%
  summarise(across(c(average_speed:coggan_tss), ~ mean(.x, na.rm = TRUE),.names = "average_{.col}"),.groups = "keep") %>%
  ungroup()

# join tibbles 
quarter_joined <- quarter_totals %>%
  full_join(quarter_averages)

activities_cp_trim <- activities_cp %>%
  select(id,age,year,quarter, gender,critical_power,w_prime,critical_power_error,w_prime_error) %>%
  unique()
  
activity_metrics <- activities_cp_trim %>%
  full_join(quarter_joined, by = c("id","year","quarter"))
  
```

# Dimensionality reduction: Principle component analysis

```{r}
pca_fit <- activity_metrics %>%
  select(where(is.numeric)) %>% # retain nymeric columns
  drop_na() %>% # need to remove all Na values
  scale() %>% # scale to zero mean and unit variance
  prcomp() # do PCA


arrow_style <- arrow(
  angle = 20, length = grid::unit(4, "pt"),
  ends = "first", type = "closed"
)

pca_fit %>%
  # extract rotation matrix
  tidy(matrix = "rotation") %>%
  pivot_wider(
    names_from = "PC", values_from = "value",
    names_prefix = "PC"
  ) %>%
  ggplot(aes(PC1, PC2)) +
  geom_segment(
    xend = 0, yend = 0,
    arrow = arrow_style
  ) +
  geom_text(aes(label = column),hjust = 1) +
  xlim(-1.5,0.5) +
  ylim(-1,1) +
  coord_fixed()

```

```{r}
pca_fit %>%
  # extract eigenvalues
  tidy(matrix = "eigenvalues") %>%
  ggplot(aes(PC, percent)) +
  geom_col() +
  scale_x_continuous(
    # create one axis tick per PC
    breaks = 1:18
  ) +
  scale_y_continuous(
    name = "variance explained",
    # format y axis ticks as percent values
    label = scales::label_percent(accuracy = 1)
  )
```








# Training metrics vs CP
```{r}
# Training duration
quarter_metrics %>%
  filter(total_workout_time <= 1000000) %>%
  ggplot(aes(x = total_workout_time, y = critical_power)) +
  geom_point(alpha = 0.5) +
  geom_smooth(method = "lm",colour = "blue")

# Training distance
quarter_metrics %>%
  filter(total_total_distance >0 & total_total_distance <= 20000) %>%
  ggplot(aes(x = total_total_distance, y = critical_power)) +
  geom_point(alpha = 0.5) +
  geom_smooth(method = "lm",colour = "blue")

# Average power 
quarter_metrics %>%
    ggplot(aes(x = average_average_power, y = critical_power)) +
  geom_point(alpha = 0.3) +
  geom_smooth(method = "lm",colour = "blue")

# Average HR
quarter_metrics %>%
  filter(average_average_hr > 50) %>%
  ggplot(aes(x = average_average_hr, y = critical_power)) +
  geom_point(alpha = 0.3) +
  geom_smooth(method = "lm",colour = "blue")
```

```{r}

```





## Average change in CP over time

```{r}
cp_stats <- activities_cp
# calculate % change in cp/w_prime for each quarter per person
  group_by(id) %>%
  arrange(year, quarter, .by_group = TRUE) %>%
  mutate(cp_pct_change = (critical_power / lag(critical_power)-1)*100,
         w_prime_pct_change = (w_prime / lag(w_prime)-1)*100)

# change in cp per quarter
cp_stats %>%
  filter(year > 1999 & year <= 2021) %>%
  group_by(year) %>%
  summarise(avg_change = mean(cp_pct_change, na.rm = TRUE)) %>%
  arrange(avg_change) %>%
  ggplot(aes(x = factor(year), y = avg_change)) +
  geom_col(fill = "#f03b20", alpha = 0.5) +
  labs(title = "Average percent change in critical power per quarter",
       x = NULL,
       y = NULL)

# change in wprime per quarter
cp_stats %>%
  filter(year > 1999 & year <= 2021) %>%
  group_by(year) %>%
  summarise(avg_change = mean(w_prime_pct_change, na.rm = TRUE)) %>%
  arrange(avg_change) %>%
  ggplot(aes(x = factor(year), y = avg_change)) +
  geom_col(fill = "#f03b20", alpha = 0.5) +
  labs(title = "Average percent change in W' per quarter",
       x = NULL,
       y = NULL)

```